server:
  port: 8089

spring:
  application:
    name: windows11
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss